### ISSUE TITLE
Vim freezes with heavy CPU usage when opening Ansible files

### ISSUE THREAD

**Issue by LeonB** [chase/vim-ansible-yaml#11]
Revert back to the previous commit fixes this issue. I'll try and see if this is related to something else in my .vimrc

---
## Solution

Ensure that ``regexpengine` is set to `0`.
The new YAML syntax is not compatible with the old engine, when `regexpengine` or `re` is set to 0.

**Comment by klaussfreire** [comment]
For me, adding 

```
set re=1
```

To the syntax file solved it. Using vim 7.4 in opensuse.

**Comment by ava-dylang** [comment]
I believe I had this issue as well.
is there some way I can tell vim only to apply this `set re=1` override when editing yaml files? I have it applying globally right now.
