### ISSUE TITLE
Closing bracket does not highlight correctly

### ISSUE THREAD

**Issue by Daemoen** [chase/vim-ansible-yaml#44]
![image](https://cloud.githubusercontent.com/assets/1039884/9283038/656403a2-4285-11e5-99a2-1101c79d2c90.png)

**Comment by Gonzih** [comment]
I still see similar issue with RainbowParentheses active. Is it issue in ansible plugin? Should I use some kind of workaround to fix that?

Thanks

![area-screenshot](https://cloud.githubusercontent.com/assets/266275/18713572/11b2701e-8013-11e6-9aaa-a479b8c6d6e7.png)

**Comment by pearofducks** [comment]
Does the issue happen without RainbowParentheses?

**Comment by Gonzih** [comment]
No, if I call RainbowParenthesesToggle brackets just become white. So I would say no issue without rainbow plugin.

**Comment by Gonzih** [comment]
I use this version btw https://github.com/kien/rainbow_parentheses.vim
