### ISSUE TITLE
Re: Maintainer Wanted

### ISSUE THREAD

**Issue by schlueter** [chase/vim-ansible-yaml#52]
I'd be game. How would you like to proceed?
##

**Comment by codeinabox** [comment]
I could add you as a maintainer if you're game

**Comment by codeinabox** [comment]
The more collaborators the better though only @chase can give you access

**Comment by schlueter** [comment]
Of course, this was a from the hip reaction to the signage.

**Comment by chase** [comment]
@schlueter If you can resolve one of the open issues, then I'll add you.
